### ISSUE TITLE
Data requirement for BacPacs

### ISSUE THREAD

**Issue by Wendy361** [barashe/bacpacs#2]
Hi, I have a question regarding the data requirement for the package. I have whole genome sequencing for the single strain bacteria. Do I have to translate this DNA sequencing data into protein to be fed in this package? Or this package can accept the DNA sequence and convert it into protein directly?

**Comment by barashe** [comment]
Hi @Wendy361 , BacPacs only supports proteomic data, as supplied in the [toy example](https://github.com/barashe/bacpacs/blob/master/toy.tar.gz).
